---

# https://docs.travis-ci.com/user/osx-ci-environment

# macOS 10.11 & 10.10
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.1
  allow_failures:
    - osx_image: xcode7.1
  fast_finish: true

install:
  # Debug info
  - python --version
  # Update Homebrew
  - brew update
  # Install Python, separate from version that ships with macOS
  - brew install python
  # Install Ansible
  - brew install ansible
  # Debug info
  - python --version
  - pip --version
  - ansible --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run test playbook
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

  # Idempotence test (run test playbook again & check output)
  # TODO: This role is particularly idempotent right now.
  # - >
  #   ansible-playbook tests/test.yml -i tests/inventory --connection=local
  #   | grep -q 'changed=0.*failed=0'
  #   && (echo 'Idempotence test: pass' && exit 0)
  #   || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
